### ISSUE TITLE
[Bug?] Petstore can be analyzed, but realworld conduit API definitions cannot be analyzed

### ISSUE THREAD

**Issue by yukihirop** [aspida/openapi2aspida#134]
## Description

Thank you for creating a nice library. ✨
However, there seems to be a slight problem. 😅

## Environment

- **Package version:**
  
  `v0.16.1`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `v12.10.0`
- **npm version:**
  
  `6.10.3`
- **yarn version:**
  
  `1.22.0`

## Additional context

[The OpenAPI definition of the conduit API](https://github.com/gothinkster/realworld/blob/master/api/swagger.json) is known worldwide in the realworld-example-app backend API, and as you can see, it is correctly recognized by the Swagger Editor.

![image](https://user-images.githubusercontent.com/11146767/115006139-7c977e80-9ee3-11eb-997f-1e9f97459b4f.png)

However, it cannot be analyzed with `openapi2aspida` .
I think that what Swagger Editor recognizes without error should be able to be analyzed.

```json
  "scripts": {
    "api:type": "openapi2aspida -i https://github.com/gothinkster/realworld/blob/master/api/swagger.json",
   }
```

```bash
$ yarn run api:type
yarn run v1.22.10
$ openapi2aspida -i https://github.com/gothinkster/realworld/blob/master/api/swagger.json
(node:8931) UnhandledPromiseRejectionWarning: ParserError: Error parsing https://github.com/gothinkster/realworld/blob/master/api/swagger.json: end of the stream or a document separator is expected at line 97, column 65:
     ... e" content="{&quot;version&quot;: &quot;4&quot;, &quot;rollouts& ...
                                         ^
    at Object.parse (/Users/yukihirop/JavaScriptProjects/vuejs-realworld-example-app/node_modules/@apidevtools/json-schema-ref-parser/lib/parsers/yaml.js:51:15)
    at getResult (/Users/yukihirop/JavaScriptProjects/vuejs-realworld-example-app/node_modules/@apidevtools/json-schema-ref-parser/lib/util/plugins.js:140:18)
    at runNextPlugin (/Users/yukihirop/JavaScriptProjects/vuejs-realworld-example-app/node_modules/@apidevtools/json-schema-ref-parser/lib/util/plugins.js:78:22)
    at /Users/yukihirop/JavaScriptProjects/vuejs-realworld-example-app/node_modules/@apidevtools/json-schema-ref-parser/lib/util/plugins.js:67:5
    at new Promise (<anonymous>)
    at Object.exports.run (/Users/yukihirop/JavaScriptProjects/vuejs-realworld-example-app/node_modules/@apidevtools/json-schema-ref-parser/lib/util/plugins.js:66:10)
    at /Users/yukihirop/JavaScriptProjects/vuejs-realworld-example-app/node_modules/@apidevtools/json-schema-ref-parser/lib/parse.js:123:13
    at new Promise (<anonymous>)
    at parseFile (/Users/yukihirop/JavaScriptProjects/vuejs-realworld-example-app/node_modules/@apidevtools/json-schema-ref-parser/lib/parse.js:111:10)
    at parse (/Users/yukihirop/JavaScriptProjects/vuejs-realworld-example-app/node_modules/@apidevtools/json-schema-ref-parser/lib/parse.js:40:26)
(node:8931) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:8931) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✨  Done in 0.92s.
```

**Comment by yukihirop** [comment]
I got a similar error when trying to automatically generate a type from a different approach.

```bash
docker run --rm openapitools/openapi-generator-cli generate -i https://github.com/gothinkster/realworld/blob/master/api/swagger.json -g typescript-fetch -o ./api
```

```bash
$ docker run --rm openapitools/openapi-generator-cli generate -i https://github.com/gothinkster/realworld/blob/master/api/swagger.json -g typescript-fetch -o ./api
Unable to find image 'openapitools/openapi-generator-cli:latest' locally
latest: Pulling from openapitools/openapi-generator-cli
bd8f6a7501cc: Pull complete
44718e6d535d: Pull complete
efe9738af0cb: Pull complete
c647a8e650d3: Pull complete
cf7f1fadeec3: Pull complete
f9fb8b5acc3c: Pull complete
87e9027cf736: Pull complete
880f1636174e: Pull complete
Digest: sha256:f709095697760d653e28caa4897da88399f57054ee7302b33680edefbf39d828
Status: Downloaded newer image for openapitools/openapi-generator-cli:latest
[main] WARN  i.s.parser.util.DeserializationUtils - Error snake-parsing yaml content
io.swagger.parser.util.DeserializationUtils$SnakeException: Exception safe-checking yaml content  (maxDepth 2000, maxYamlAliasesForCollections 2147483647)
	at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:387)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437)
	at io.swagger.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:205)
	at io.swagger.parser.Swagger20Parser.deserializeYaml(Swagger20Parser.java:85)
	at io.swagger.parser.Swagger20Parser.readWithInfo(Swagger20Parser.java:64)
	at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:34)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:89)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:523)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 97, column 65:
     ... e" content="{&quot;version&quot;: &quot;4&quot;, &quot;rollouts& ...
                                         ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:870)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358)
	at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:250)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:253)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:87)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
	at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:366)
	... 13 common frames omitted
[main] WARN  i.s.parser.util.DeserializationUtils - Error snake-parsing yaml content
io.swagger.parser.util.DeserializationUtils$SnakeException: Exception safe-checking yaml content  (maxDepth 2000, maxYamlAliasesForCollections 2147483647)
	at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:387)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437)
	at io.swagger.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:205)
	at io.swagger.parser.Swagger20Parser.deserializeYaml(Swagger20Parser.java:85)
	at io.swagger.parser.Swagger20Parser.readWithInfo(Swagger20Parser.java:64)
	at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:44)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:89)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:523)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 97, column 65:
     ... e" content="{&quot;version&quot;: &quot;4&quot;, &quot;rollouts& ...
                                         ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:870)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358)
	at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:250)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:253)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:87)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
	at io.swagger.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:366)
	... 13 common frames omitted
[main] ERROR i.s.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (StringReader); line: 7, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1917)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:773)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:194)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
	at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:94)
	at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:44)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:89)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:523)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
[main] ERROR i.s.parser.SwaggerCompatConverter - failed to read resource listing
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (StringReader); line: 7, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1917)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:773)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4231)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2711)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:194)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:123)
	at io.swagger.parser.SwaggerCompatConverter.readWithInfo(SwaggerCompatConverter.java:94)
	at io.swagger.parser.SwaggerParser.readWithInfo(SwaggerParser.java:44)
	at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:89)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:523)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:573)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:432)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - Output directory (/./api) does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
Exception in thread "main" java.lang.RuntimeException: Issues with the OpenAPI input. Possible causes: invalid/missing spec, malformed JSON/YAML files, etc.
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:836)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:440)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

**Comment by solufa** [comment]
Thanks for posting this.
https://github.com/gothinkster/realworld/blob/master/api/swagger.json is a URL that returns HTML, not JSON.

Changing it to the following will work.

```json
  "scripts": {
    "api:type": "openapi2aspida -i https://raw.githubusercontent.com/gothinkster/realworld/master/api/swagger.json",
   }
```

**Comment by yukihirop** [comment]
Oh... sorry...

Thank you. 👍 

```
$ yarn api:type
yarn run v1.22.10
$ openapi2aspida -i https://raw.githubusercontent.com/gothinkster/realworld/master/api/swagger.json
api/$api.ts was built successfully.
api/articles/$api.ts was built successfully.
api/articles/feed/$api.ts was built successfully.
api/profiles/$api.ts was built successfully.
api/tags/$api.ts was built successfully.
api/user/$api.ts was built successfully.
api/users/$api.ts was built successfully.
api/users/login/$api.ts was built successfully.
✨  Done in 0.76s.
```
