### ISSUE TITLE
can't handle query that contains "."

### ISSUE THREAD

**Issue by yuki-js** [aspida/openapi2aspida#150]
## Description

An error occurs if input file is as follows
```
    "/v1/channels/abandon/{channel_point.funding_txid_str}/{channel_point.output_index}": {
      "delete": {
        // ....
        "parameters": [
          {
            "name": "channel_point.funding_txid_str",
            "in": "path",
            // ....
          },
```

## Environment

- **Package version:**
  
  `v0.16.4`
- **OS:**
  
  - [ ] Linux
  - [ ] Windows
  - [x] macOS
- **Node.js version:**
  
  `v14.17.1`
- **npm version:**
  
  ``

## Additional context
error log
```
(node:36592) UnhandledPromiseRejectionWarning: Error: aspida ERROR '_'chan_point.funding_txid_str'@string' does not match '/^_[a-zA-Z][a-zA-Z0-9_]*(@number|@string)?((\.|%[0-9a-fA-F]{2})[a-zA-Z0-9]+)?$/'.
    at /home/yjsnpi/codes/NayutaBox/node_modules/aspida/dist/createTemplateValues.js:42:27
    at Array.map (<anonymous>)
    at createApiString (/home/yjsnpi/codes/NayutaBox/node_modules/aspida/dist/createTemplateValues.js:31:14)
    at /home/yjsnpi/codes/NayutaBox/node_modules/aspida/dist/createTemplateValues.js:66:49
    at Array.map (<anonymous>)
    at createApiString (/home/yjsnpi/codes/NayutaBox/node_modules/aspida/dist/createTemplateValues.js:31:14)
    at /home/yjsnpi/codes/NayutaBox/node_modules/aspida/dist/createTemplateValues.js:66:49
    at Array.map (<anonymous>)
    at createApiString (/home/yjsnpi/codes/NayutaBox/node_modules/aspida/dist/createTemplateValues.js:31:14)
    at /home/yjsnpi/codes/NayutaBox/node_modules/aspida/dist/createTemplateValues.js:66:49
```

**Comment by hashue** [comment]
こちら依存ライブラリであるaspidaの問題のようなので、そちらを対応するまでお待ちください
